spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

application:
  jwt:
    access-token-expiration-after-days: 60
    refresh-token-expiration-after-days: 1
    token-prefix: "Bearer "